language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install -r misty2/test-requirements.txt
  - pip install -r misty2/requirements.txt

script:
  - pylint -E misty2/mistyrest.py

after_success:
- if test "$TRAVIS_PULL_REQUEST" = "false"; then rerobots submit-ci-job --repo-branch $TRAVIS_BRANCH --repo-ref $TRAVIS_COMMIT XTiJi-7b_TuYLRrKtuusMA; fi

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
